from django.db import models

# Generated by Django A.B on YYYY-MM-DD HH:MM
import datetime

from django.db import migrations

'''
Чтобы избежать ошибку: Django migration error :
you cannot alter to or from M2M fields, or add or remove through= on M2M fields

ДЕЛАЛ по ПРИМЕРУ - пункт 106:
https://stackoverflow.com/questions/26927705/django-migration-error-you-cannot-alter-to-or-from-m2m-fields-or-add-or-remove
'''


# 1.
# Создаем СКВОЗНУЮ МОДЕЛЬ и запускаем (но пока не помещаем свойство "through"
# в поле Group.members): "py manage.py makemigrations"

class Person(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class Group(models.Model):
    name = models.CharField(max_length=128)
    # members = models.ManyToManyField(Person) # <-- no through property yet!
    members = models.ManyToManyField(Person, through='Membership')

    # 3.
    # удалить поле в модели и запустить с помощью команды "py manage.py makemigrations Group",
    # 0002_remove_group_members.py
    # теперь будет выглядеть следующим образом:
    # class Group(models.Model):
    #     name = models.CharField(max_length=128)

    # 4.
    # Добавим поле в модель но терень уже СО СВОЙСТВОМ "through"
    # 0003_group_members.py
    # и запустим с помощью команды "py manage.py makemigrations"

    # теперь будет выглядеть следующим образом:
    # class Group(models.Model):
    #     name = models.CharField(max_length=128)
    # members = models.ManyToManyField(Person, through='Membership')

    # 5.
    # Только теперь можно выполнить "py manage.py migrate" !!!
    # Обновить БД и проверить таблицы в базе данных !

    def __str__(self):
        return self.name


class Membership(models.Model): # <--- through model
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    date_joined = models.DateField()


# 2.
# Создайте ПУСТУЮ МИГРАЦИЮ с помощью команды "py manage.py makemigrations persons"
# и создайте скрипт преобразования в Python который создает новые отношения ()
# для старого поля ().

def create_through_relations(apps, schema_editor):
    '''
    Подробно см.
    https://docs.djangoproject.com/en/2.0/ref/migration-operations/#django.db.migrations.operations.RunPython
    '''
    Group = apps.get_model('persons', 'Group')
    Membership = apps.get_model('persons', 'Membership')
    for group in Group.objects.all():
        for member in group.members.all():
            Membership(
                person=member,
                group=group,
                date_joined=datetime.date.today()
            ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_create_models'),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),
    ]


'''
Теперь вам нужно изменить создание членов по-новому в вашем коде - 
сквозной моделью. Подробнее об этом здесь:
https://docs.djangoproject.com/en/2.0/topics/db/models/#extra-fields-on-many-to-many-relationships
'''

